version: "3.7"

volumes:
  postgresql_data:
  odoo_data:
  odoo_filestore:
  odoo_sessions:

networks:
  odoo_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.45.0.0/16

services:
  odoo:
    build: .
    container_name: odoo
    user: root
    ports:
      - "8069:8069"
      - "8071:8071"
    depends_on:
      - db
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
      - odoo_filestore:/opt/odoo/filestore
      - odoo_sessions:/opt/odoo/sessions
    networks:
      - odoo_network

  db:
    container_name: db
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - odoo_network

